## __Project Overview & Objectives__

This project aims to transform raw, fragmented real-estate data into an Investment Intelligence Engine. Instead of just looking at prices, we analyze risk, space efficiency, and demographic demand to help investors make data-backed decisions.

##### __*Strategic Goals*__
+ **Risk Mitigation:** Identify "High-Risk" vs. "Safe & Verified" assets using RERA and age data.
+ **Value Discovery:** Find "Bargains" where properties are priced 15% below the locality average.
+ **Utility Optimization:** Analyze space efficiency and parking ratios to identify high-returns rental assets.
+ **Market Segmentation:** Map the supply of "Family-Sized" vs. "Bachelor/Studio" units to find market gaps.
+ **Scarcity Analysis:** Isolate "Rare Assets" (low-density homes) in high-density urban markets for long-term land appreciation.

### __Data Ingestion__

In [223]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

To ensure data integrity and scalability, I developed a custom Python ingestion script to migrate the raw real estate dataset into a **MySQL Relational Database**.

In [ ]:
# Checking database connection, tables in database, and row counts.

engine = create_engine("mysql+pymysql://root:YOUR_PASSWORD_HERE@localhost:3306/estate")

try:
    tables = pd.read_sql_query("SHOW TABLES", engine)
    
    print("Connection Successful!")
    print("Tables found in 'estate' database:")
    print(tables)

except Exception as e:
    print(f"Connection Failed: {e}")

print("\n--- Database Overview: Preview & Counts ---")

for table_name in tables.iloc[:, 0]:
    
    count_df = pd.read_sql_query(f"SELECT COUNT(*) as total FROM {table_name}", engine)
    total_rows = count_df['total'][0]
    
    preview_df = pd.read_sql_query(f"SELECT * FROM {table_name} LIMIT 5", engine)
    
    print("-" * 50) 
    print(f"TABLE: {table_name}")
    print(f"TOTAL ROWS: {total_rows}")
    display(preview_df)
    print("\n")

Connection Successful!
Tables found in 'estate' database:
  Tables_in_estate
0       test_part1
1       test_part2
2      train_part1
3      train_part2

--- Database Overview: Preview & Counts ---
--------------------------------------------------
TABLE: test_part1
TOTAL ROWS: 2364

,listingid,city,locality,propertytype,bhk,bathrooms,balconies,furnishing,superbuiltuparea_sqft,builtuparea_sqft,...,parking,buildingtype,yearbuilt,ageyears,facing,amenitiescount,isreraregistered,reraid,latitude,longitude
0,HP501139,Kolkata,Tollygunge,Row House,2,2.0,1.0,Semi-Furnished,1775,1310,...,Covered,Standalone Building,2010.0,15,North-West,4,0,None,22.508916,88.426249
1,HP501630,Pune,Hinjawadi,Apartment,2,3.0,1.0,Unfurnished,1434,1140,...,Open,Standalone Building,2021.0,4,North-West,8,1,PUN-RERA-4220-31,18.464449,73.897222
2,HP501608,Ahmedabad,Bodakdev,Apartment,1,2.0,2.0,Semi-Furnished,883,728,...,Basement,Mid Rise,2002.0,23,West,8,1,AHM-RERA-2634-72,22.933611,72.584989
3,HP501979,Chennai,T Nagar,Independent House,5,6.0,1.0,Furnished,3840,3096,...,Covered,Bungalow,2022.0,3,North-West,4,0,None,12.985430,80.259339
4,HP501399,Ahmedabad,Maninagar,Apartment,3,4.0,1.0,Semi-Furnished,1922,1629,...,Open,Mid Rise,2003.0,22,North,9,0,None,22.987366,72.672125

--------------------------------------------------
TABLE: test_part2
TOTAL ROWS: 2364

,listingid,city,locality,propertytype,bhk,bathrooms,balconies,furnishing,superbuiltuparea_sqft,builtuparea_sqft,...,parking,buildingtype,yearbuilt,ageyears,facing,amenitiescount,isreraregistered,reraid,latitude,longitude
0,HP501287,Delhi NCR,Gurugram-Sector 56,Apartment,3,4.0,1.0,Unfurnished,2747,2170,...,Covered,Mid Rise,2019.0,6,South,7,1,DEL-RERA-1234-67,28.375415,76.907933
1,HP501726,Ahmedabad,Bopal,Independent House,5,6.0,1.0,Unfurnished,4272,3248,...,Covered,Gated Community,2017.0,8,South,10,1,AHM-RERA-4988-49,23.119591,72.429255
2,HP501011,Kolkata,Tollygunge,Villa,6,7.0,1.0,Unfurnished,3414,2670,...,Basement,Bungalow,2012.0,13,South,6,0,None,22.489030,88.473278
3,HP500910,Hyderabad,Manikonda,Penthouse,4,4.0,2.0,Unfurnished,2040,1729,...,Covered,High Rise,2005.0,20,West,6,1,HYD-RERA-1196-16,17.345639,78.491808
4,HP501536,Hyderabad,Madhapur,Apartment,2,3.0,1.0,Semi-Furnished,1720,1392,...,Open,Standalone Building,2007.0,18,South,6,1,HYD-RERA-2304-21,17.448087,78.588054

--------------------------------------------------
TABLE: train_part1
TOTAL ROWS: 2364

,listingid,city,locality,propertytype,bhk,bathrooms,balconies,furnishing,superbuiltuparea_sqft,builtuparea_sqft,...,buildingtype,yearbuilt,ageyears,facing,amenitiescount,isreraregistered,reraid,latitude,longitude,price_inr
0,HP01139,Bengaluru,None,Villa,3,3.0,2.0,Semi-Furnished,1576,1299,...,Bungalow,2018.0,7,South-East,3,1,BEN-RERA-9928-63,12.877154,77.656243,17770000
1,HP01630,Kolkata,Rajarhat,Apartment,1,2.0,1.0,Unfurnished,1098,870,...,Mid Rise,2010.0,15,North-West,9,1,KOL-RERA-6820-36,22.584035,88.440364,7130000
2,HP01608,Kolkata,Salt Lake,Apartment,1,2.0,3.0,Unfurnished,863,710,...,High Rise,2006.0,19,South,6,1,KOL-RERA-5304-84,22.535687,88.416707,5920000
3,HP01979,MMR,Goregaon East,Apartment,2,3.0,NaN,Furnished,1135,952,...,High Rise,2025.0,0,North-East,7,0,None,NaN,72.877790,19140000
4,HP01399,Hyderabad,Madhapur,Apartment,3,4.0,1.0,Semi-Furnished,2662,2176,...,Standalone Building,2010.0,15,North,6,1,HYD-RERA-7537-95,17.444963,78.431430,20300000

--------------------------------------------------
TABLE: train_part2
TOTAL ROWS: 2364

,listingid,city,locality,propertytype,bhk,bathrooms,balconies,furnishing,superbuiltuparea_sqft,builtuparea_sqft,...,buildingtype,yearbuilt,ageyears,facing,amenitiescount,isreraregistered,reraid,latitude,longitude,price_inr
0,HP01287,Bengaluru,Banashankari,Apartment,3,3.0,2.0,Semi-Furnished,1816,1386,...,Standalone Building,2018.0,7,South,9,1,BEN-RERA-3063-23,12.822958,77.759009,15060000
1,HP01726,Delhi NCR,Faridabad-Sector 21,Apartment,2,2.0,2.0,Semi-Furnished,1579,1205,...,Standalone Building,2009.0,16,South-West,8,1,DEL-RERA-8739-21,28.563276,76.992152,12570000
2,HP01011,Pune,Hinjawadi,Independent House,3,3.0,1.0,Unfurnished,2073,1711,...,Standalone Building,2014.0,11,North-East,4,1,PUN-RERA-4033-88,18.468168,NaN,17470000
3,HP00910,Chennai,Velachery,Villa,4,5.0,1.0,Unfurnished,3637,3031,...,Bungalow,2006.0,19,North-West,5,1,CHE-RERA-9763-53,12.922412,80.312701,36280000
4,HP01536,Chennai,T Nagar,Penthouse,6,7.0,2.0,Unfurnished,3973,2982,...,High Rise,2008.0,17,North,7,1,CHE-RERA-8666-20,13.061543,80.329035,36640000

### __Data Wrangling__

In [225]:
# Checking column names & data type before merging.
df1 = pd.read_sql("SELECT * FROM train_part1 LIMIT 1", engine)
df2 = pd.read_sql("SELECT * FROM train_part2 LIMIT 1", engine)
same_columns = list(df1.columns) == list(df2.columns)
same_dtypes = df1.dtypes.equals(df2.dtypes)

print(f"Columns Match: {same_columns}")
print(f"Data Types Match: {same_dtypes}")

Columns Match: True
Data Types Match: True

In [226]:
# Merging (vertically) dataset df1 and df2 together.
querry = """
    SELECT * FROM train_part1
    UNION ALL
    SELECT * FROM train_part2;
"""
df_union = pd.read_sql(querry, con = engine)
print(f"Merged Dataframe Shape: {df_union.shape}\n")
display(df_union.head())

Merged Dataframe Shape: (4728, 24)

,listingid,city,locality,propertytype,bhk,bathrooms,balconies,furnishing,superbuiltuparea_sqft,builtuparea_sqft,...,buildingtype,yearbuilt,ageyears,facing,amenitiescount,isreraregistered,reraid,latitude,longitude,price_inr
0,HP01139,Bengaluru,None,Villa,3,3.0,2.0,Semi-Furnished,1576,1299,...,Bungalow,2018.0,7,South-East,3,1,BEN-RERA-9928-63,12.877154,77.656243,17770000
1,HP01630,Kolkata,Rajarhat,Apartment,1,2.0,1.0,Unfurnished,1098,870,...,Mid Rise,2010.0,15,North-West,9,1,KOL-RERA-6820-36,22.584035,88.440364,7130000
2,HP01608,Kolkata,Salt Lake,Apartment,1,2.0,3.0,Unfurnished,863,710,...,High Rise,2006.0,19,South,6,1,KOL-RERA-5304-84,22.535687,88.416707,5920000
3,HP01979,MMR,Goregaon East,Apartment,2,3.0,NaN,Furnished,1135,952,...,High Rise,2025.0,0,North-East,7,0,None,NaN,72.877790,19140000
4,HP01399,Hyderabad,Madhapur,Apartment,3,4.0,1.0,Semi-Furnished,2662,2176,...,Standalone Building,2010.0,15,North,6,1,HYD-RERA-7537-95,17.444963,78.431430,20300000

*From the above analysis we conclude some points:*
- This synthetic dataset comprises residential property listings across multiple Indian metropolitan regions. It includes both training (train_part1 & train_part2) and test (test_part1 & test_part2) dataset.
- Training subset has target prices whereas test subset intended for prediction. So for our analysis we consider only training subset.  
- Instead of treating each dataset separately I combined "train_part1" and "train_part2" table together so that I get unified master dataset of ~5,000 records. This allowed for deeper exploratory analysis and more robust insights into the Pan-India real estate market.
---

In [227]:
df_union.columns

Index(['listingid', 'city', 'locality', 'propertytype', 'bhk', 'bathrooms',
       'balconies', 'furnishing', 'superbuiltuparea_sqft', 'builtuparea_sqft',
       'carpetarea_sqft', 'floor', 'totalfloors', 'parking', 'buildingtype',
       'yearbuilt', 'ageyears', 'facing', 'amenitiescount', 'isreraregistered',
       'reraid', 'latitude', 'longitude', 'price_inr'],
      dtype='object')

In [228]:
# List of columns to keep
cols_to_keep = ['listingid', 'city', 'locality', 'propertytype', 'bhk', 'bathrooms',
       'superbuiltuparea_sqft','carpetarea_sqft', 'totalfloors', 'parking', 'buildingtype',
       'yearbuilt', 'ageyears', 'amenitiescount', 'isreraregistered',
       'reraid', 'latitude', 'longitude', 'price_inr']

# Filtered Columns
df_filtered = df_union[cols_to_keep].copy()
print(f"Columns left: {len(df_filtered.columns)}")

Columns left: 19

*We also filtered out the columns which are not releated to our business problem. We keep following columns for our further analysis:*
+ Entity Key: 'ListingID' is unique identifier for property listing.
+ Geography: 'City' and 'Locality' provide hierarchial location; 'Latitude' and 'Longitude' enable geospatial work.
+ Physical Specs: PropertyType, BHK, Bathrooms, Areas (Super/Carpet), TotalFloor, Parking, BuildingType, YearBuilt and AgeYears.
+ Amenities: AmenitiesCount aggregates available features.
+ Compliance: IsRERARegistered and RERAID capture regulatory registration metadata.
+ Target: Price_INR represents listed or transacted value in INR. 
---

### __Data Cleaning__

We identify and remove duplicate listings to ensure land integrity, handle missing values (imputation), and fix inconsistencies in city names and data types to ensure our analysis is accurate.

In [229]:
# Checking columns, Not-Null count and data types.
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4728 entries, 0 to 4727
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   listingid              4728 non-null   object
 1   city                   4678 non-null   object
 2   locality               4658 non-null   object
 3   propertytype           4728 non-null   object
 4   bhk                    4728 non-null   int64
 5   bathrooms              4674 non-null   float64
 6   superbuiltuparea_sqft  4728 non-null   int64
 7   carpetarea_sqft        4728 non-null   int64
 8   totalfloors            4728 non-null   int64
 9   parking                4288 non-null   object
 10  buildingtype           4728 non-null   object
 11  yearbuilt              4689 non-null   float64
 12  ageyears               4728 non-null   int64
 13  amenitiescount         4728 non-null   int64
 14  isreraregistered       4728 non-null   int64
 15  reraid                 3778 non-null   object
 16  latitude               4678 non-null   float64
 17  longitude              4669 non-null   float64
 18  price_inr              4728 non-null   int64
dtypes: float64(4), int64(8), object(7)
memory usage: 701.9+ KB

In [230]:
# Checking duplicates in primary key (i.e. ListingID).
print(df_filtered.duplicated(subset=['listingid']), f"Total duplicate records: {df_filtered.duplicated(subset=['listingid']).sum()}", sep='\n\n')

0       False
1       False
2       False
3       False
4       False
        ...
4723     True
4724     True
4725     True
4726     True
4727     True
Length: 4728, dtype: bool

Total duplicate records: 2364

In [231]:
composite_columns = ['city', 'locality', 'price_inr', 'superbuiltuparea_sqft']
df_filtered.duplicated(composite_columns).sum()

np.int64(0)

##### __*Duplicates Handling*__
- When I checked for duplicates in primary key column i.e. 'ListingID', it is found that single 'ListingID' is use for two different property i.e having the same ID for a flat in Mumbai and a house in Delhi. ListingID should ideally point to one specific home as it is unique identifier.  
- The duplicate ListingIDs indicates that the data collection system reused IDs for different properties in different regions. So for finding actual duplicates I used "Composite Key Duplication Strategy" i.e. a row is only a duplicate if multiple columns match exactly (e.g., City + Locality + Price_INR + SuperBuiltUpArea_sqft).
- This strategy helps me to conclude that there are no duplicates present in the record even though "ListingID" is same.
---

In [232]:
# Checking total nulls & percentage per column.
null_counts = df_filtered.isnull().sum()
null_pct = round((null_counts/len(df_filtered))*100,2)

missing_data = pd.DataFrame({'Total Nulls': null_counts, 'Percentage %': null_pct})
display(missing_data)

                       Total Nulls  Percentage %
listingid                        0          0.00
city                            50          1.06
locality                        70          1.48
propertytype                     0          0.00
bhk                              0          0.00
bathrooms                       54          1.14
superbuiltuparea_sqft            0          0.00
carpetarea_sqft                  0          0.00
totalfloors                      0          0.00
parking                        440          9.31
buildingtype                     0          0.00
yearbuilt                       39          0.82
ageyears                         0          0.00
amenitiescount                   0          0.00
isreraregistered                 0          0.00
reraid                         950         20.09
latitude                        50          1.06
longitude                       59          1.25
price_inr                        0          0.00

In [233]:
# Dropping rows where both city and locality have NaN values
df_filtered_drop_null = df_filtered.dropna(subset=['city', 'locality'])

# Removing duplicates in locality only for mapping purpose
mapping = df_filtered_drop_null.drop_duplicates('locality')
# Making mapping dictionary
mapping_dict = pd.Series(mapping.city.values, index=mapping.locality.values).to_dict()
# Filling missing cities using the mapping
df_filtered['city'] = df_filtered['city'].fillna(df_filtered['locality'].map(mapping_dict))

# Checking how many values are filled
remaining_nulls = df_filtered['city'].isnull().sum()
print(f"Cities recovered: {50 - remaining_nulls}")

Cities recovered: 50

In [234]:
# Imputing missing values for locality column.
df_filtered['locality'] = df_filtered['locality'].fillna('Unknown')

In [235]:
# Imputing Missing Values for bathrooms column.
df_filtered['bathrooms'] = df_filtered.groupby('bhk')['bathrooms'].transform(lambda x: x.fillna(x.median()))

In [236]:
# Imputing missing values for latitude and longitude column using city column.

# Before imputing with we are checking if outliers are present in latitiue and longitude column.
outliers = df_filtered[(df_filtered['latitude'] < 6) | (df_filtered['latitude'] > 37) | 
              (df_filtered['longitude'] < 68) | (df_filtered['longitude'] > 97)]
print(f"Properties with physically impossible Indian coordinates: {len(outliers)}")

# Imputing with mean
city_coordinates = df_filtered.groupby('city')[['latitude', 'longitude']].transform('mean')
df_filtered['latitude'] = df_filtered['latitude'].fillna(city_coordinates['latitude'])
df_filtered['longitude'] = df_filtered['longitude'].fillna(city_coordinates['longitude'])

Properties with physically impossible Indian coordinates: 0

In [237]:
# Imputing missing values for reraid column using IsRERARegisterd column.
df_filtered['reraid'] = df_filtered['reraid'].str.strip().replace(['nan', 'None', ''], np.nan)
# Case A: RERA not registered.
df_filtered.loc[df_filtered['isreraregistered'] == 0, 'reraid'] = 'Not Applicable'
# Case B: RERA registered but ID not provided.
df_filtered.loc[(df_filtered['isreraregistered'] == 1) & (df_filtered['reraid'].isna()), 'reraid'] = 'ID Not Provided'

In [238]:
# Imputing missing values for yearbuilt using ageyears column.
df_filtered['yearbuilt'] = df_filtered['yearbuilt'].replace(0, np.nan)
df_filtered['year_calculated'] = 2025 - df_filtered['ageyears']
df_filtered['yearbuilt'] = df_filtered['yearbuilt'].fillna(df_filtered['year_calculated'])

df_filtered.drop(columns=['year_calculated'], inplace=True)

In [239]:
# Imputing missing values in parking column using mode (most frequent)

# First dropping off any NaN in parking column before finding most common.
parking_drop_null = df_filtered.dropna(subset=['parking']).groupby('buildingtype')['parking']

# Applying mode and making mapping dictionary.
parking_mapping = parking_drop_null.apply(lambda x: x.mode()[0]).to_dict() # .mode() returns list, [0] choose first most common

print("Parking Logic:")
for b_type, p_type in parking_mapping.items():
    print(f" - {b_type} usually has {p_type} parking")

df_filtered['parking'] = df_filtered['parking'].fillna(df_filtered['buildingtype'].map(parking_mapping))

Parking Logic:
 - Bungalow usually has Covered parking
 - Gated Community usually has Covered parking
 - High Rise usually has Covered parking
 - Low Rise usually has Open parking
 - Mid Rise usually has Covered parking
 - Standalone Building usually has Open parking

In [240]:
# Final check for missing values
df_filtered.isnull().sum()

listingid                0
city                     0
locality                 0
propertytype             0
bhk                      0
bathrooms                0
superbuiltuparea_sqft    0
carpetarea_sqft          0
totalfloors              0
parking                  0
buildingtype             0
yearbuilt                0
ageyears                 0
amenitiescount           0
isreraregistered         0
reraid                   0
latitude                 0
longitude                0
price_inr                0
dtype: int64

##### __*Missing Data Imputation*__
- If the price is missing, we cannot fulfill our goal of "best price" or "affordability." If the city/locality is missing, we can't map it. It is found that 50 cities and 70 localities are missing.
- We cannot impute locality or price value if it is missing but we can impute the City using the Locality, provided that the same locality exists elsewhere in the dataset with a city name attached.
- Used cross-reference imputation to recover missing City values based on known Locality mappings, maximizing the dataset's geographic utility.
- For remaining 70 missing Localities, used 'Unknown' placeholder to preserve price and area data for aggregate city-level analysis.
- A 1-BHK usually has 1 bathroom, while a 4-BHK has 3 or 4. We have imputed the missing values using median based on the BHK count.
- We have calculated the average (mean) Latitude and Longitude for each city and use those values to fill the gaps. This ensures that even if we don't know the exact street, the property at least appears in the correct city on the map. If we impute it using locality column then it gave us 90% accuracy but since, for remaining 70 missing Localities, used 'Unknown' placeholder so we used "City-Centroid" Imputation Strategy.
- For filling missing values in 'reraid' column we used two cases: 
    + Case 1: if a property is not registered, it shouldn't have an ID. 
    + Case 2: If it is registered but the ID is missing, it should flag it as "ID Not Provided" rather than leaving it as a NaN.
- Some 'year of built' for properties were missing but the age of property was given so we imputed missing values for 'YearBuilt' using logic: "2025 - age of property"
- We impute missing values in parking column using "Mode" (the most frequent value) of parking for each building type. For example, a "High Rise" is much more likely to have "Basement" or "Covered" parking than a "Standalone Building.
---

In [241]:
# Stripping White Spaces in text Columns.
text_cols = df_filtered.select_dtypes(include=['object']).columns
for col in text_cols:
    df_filtered[col] = df_filtered[col].astype(str).str.strip()

print(f"White spaces stripped from {len(text_cols)} columns.")

White spaces stripped from 7 columns.

In [242]:
# Fixing data inconsitancy,
df_filtered['price_inr'] = pd.to_numeric(df_filtered['price_inr'], errors='coerce').astype(float)
df_filtered['superbuiltuparea_sqft'] = pd.to_numeric(df_filtered['superbuiltuparea_sqft'], errors='coerce').astype(float)
df_filtered['carpetarea_sqft'] = pd.to_numeric(df_filtered['carpetarea_sqft'], errors='coerce').astype(float)
df_filtered['yearbuilt'] = pd.to_numeric(df_filtered['yearbuilt'], errors='coerce').astype(int)
df_filtered['bathrooms'] = pd.to_numeric(df_filtered['bathrooms'], errors='coerce').astype(int)
df_filtered['isreraregistered'] = df_filtered['isreraregistered'].map({1:'Yes',0:'No'}).astype(object)
print("Data types standardized.\n")

# Checking logic inconsistancy
area_errors = df_filtered[df_filtered['carpetarea_sqft'] > df_filtered['superbuiltuparea_sqft']]
price_errors = df_filtered[df_filtered['price_inr'] < 100000]
year_errors = df_filtered[df_filtered['yearbuilt'] > 2025]

print("Total Logical Inconsistency:")
print(len(area_errors), len(price_errors), len(year_errors), sep=',')

Data types standardized.

Total Logical Inconsistency:
0,0,0

In [243]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4728 entries, 0 to 4727
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   listingid              4728 non-null   object
 1   city                   4728 non-null   object
 2   locality               4728 non-null   object
 3   propertytype           4728 non-null   object
 4   bhk                    4728 non-null   int64
 5   bathrooms              4728 non-null   int64
 6   superbuiltuparea_sqft  4728 non-null   float64
 7   carpetarea_sqft        4728 non-null   float64
 8   totalfloors            4728 non-null   int64
 9   parking                4728 non-null   object
 10  buildingtype           4728 non-null   object
 11  yearbuilt              4728 non-null   int64
 12  ageyears               4728 non-null   int64
 13  amenitiescount         4728 non-null   int64
 14  isreraregistered       4728 non-null   object
 15  reraid                 4728 non-null   object
 16  latitude               4728 non-null   float64
 17  longitude              4728 non-null   float64
 18  price_inr              4728 non-null   float64
dtypes: float64(5), int64(6), object(8)
memory usage: 701.9+ KB

##### __*Data Inconsistencies Audit*__
- Converted numerical features (e.g., YearBuilt from float to integer) to ensure mathematical accuracy and prevent visual errors in Power BI.
- Transformed IsRERARegistered values from binary (0/1) to human-readable format (No/Yes) to improve dashboard accessibility.
- Implemented cross-column consistency checks, ensuring CarpetArea does not exceed SuperBuiltUpArea, YearBuilt cannot be in the future (2026+), and Prices shouldn't be suspiciously less than 1 Lac.
---

### __Feature Engineering__
We will create calculated columns to supplement the raw data, allowing for a more granular and insightful analysis.

In [244]:
# 1. Price per Sqft
df_filtered['price_per_sqft'] = df_filtered['price_inr'] / df_filtered['superbuiltuparea_sqft']

In [245]:
# 2. Locality Avg Price per Sqft

# Calculate how many properties are in each locality
df_filtered['group_count'] = df_filtered.groupby(['city', 'locality', 'propertytype', 'buildingtype'])['price_per_sqft'].transform('count')

# Calculate both benchmarks
df_filtered['initial_benchmark'] = df_filtered.groupby(['city', 'locality', 'propertytype', 'buildingtype'])['price_per_sqft'].transform('median')
df_filtered['final_benchmark'] = df_filtered.groupby(['city', 'locality'])['price_per_sqft'].transform('median')

# Fallback: Use initial_benchmark if count > 3, otherwise use final_benchmark
df_filtered['locality_avg_price_per_sqft'] = np.where(df_filtered['group_count'] > 3, 
                                 df_filtered['initial_benchmark'], 
                                 df_filtered['final_benchmark'])

In [246]:
# 3. Value Gap (how much specific property diverge from average market price)
df_filtered['price_deviation_pct'] = ((df_filtered['price_per_sqft'] - df_filtered['locality_avg_price_per_sqft']) / df_filtered['locality_avg_price_per_sqft'] ) * 100

# Dropping helper column
df_filtered.drop(columns=['initial_benchmark', 'final_benchmark', 'group_count'], inplace=True)

In [247]:
# 4.Price category based on 'price_deviation_pct'

# Minimum and maximum of price deviation percentage
print(df_filtered['price_deviation_pct'].min(), df_filtered['price_deviation_pct'].max(), sep=',' ,end='\n\n')

bins = [-40, -15, 15, 35, 60]
labels = ['Underpriced', 'Fair Market Value', 'Premium', 'Overpriced']
df_filtered['price_category'] = pd.cut(df_filtered['price_deviation_pct'], bins=bins, labels=labels)
print(df_filtered['price_category'].value_counts())

-30.78131739898382,46.87773254759911

price_category
Fair Market Value    4046
Premium               400
Underpriced           265
Overpriced             17
Name: count, dtype: int64

In [248]:
# 5. Land Overlap Risk
# First ensuring that locality in not unknown, since we have imputed missing values as 'Unknown'
real_coords_mask = (df_filtered['locality'] != 'Unknown')
coord_counts = df_filtered[real_coords_mask].groupby(['latitude', 'longitude'])['listingid'].transform('count')

df_filtered['land_overlap_risk'] = 'Low Risk'
df_filtered.loc[real_coords_mask & (coord_counts > 1), 'land_overlap_risk'] = 'High Risk'
df_filtered.loc[df_filtered['locality'] == 'Unknown', 'land_overlap_risk'] = 'Inexact Location'

print(df_filtered['land_overlap_risk'].value_counts())

land_overlap_risk
Low Risk            4658
Inexact Location      70
Name: count, dtype: int64

In [249]:
# 6. Structural Life Stage
def classify_life_stage(row):
    age = row['ageyears']
    building_type = str(row['buildingtype']).lower()
    
    # Apartments / High-Rises
    if 'rise' in building_type or 'community' in building_type:
        if age <= 10: return 'New'
        if age <= 25: return 'Mid-Life'
        if age <= 40: return 'Aging'
        return 'Redevelopment Needed'
    
    # Standalone Houses / Bungalow
    else:
        if age <= 15: return 'New'
        if age <= 35: return 'Mid-Life'
        if age <= 50: return 'Aging'
        return 'Redevelopment Needed'

df_filtered['structural_life_stage'] = df_filtered.apply(classify_life_stage, axis=1)

In [250]:
# 7. Safety Ratings
def safety_checks(row):
    penalty_points = 0

    # RERA unregistered
    if row['isreraregistered'] == 'No': penalty_points += 50
    elif row['reraid'] == 'ID Not Provided': penalty_points += 20

    # Suspiciously low price (maybe scam)
    if row['price_deviation_pct'] <= -40: penalty_points += 25

    # Land integrity
    if row['land_overlap_risk'] == 'High Risk': penalty_points += 40
    elif row['land_overlap_risk'] == 'Inexact Location': penalty_points += 10

    # Aging checks
    if row['structural_life_stage'] == 'Redevelopment Needed': penalty_points += 40 # High risk of major repairs
    elif row['structural_life_stage'] == 'Aging': penalty_points += 20 # Medium risk, requires audit

    # Final Categorization
    if penalty_points >= 50: return 'High Risk'
    elif penalty_points >= 25: return 'Caution'
    return 'Verified & Safe'  

df_filtered['safety_ratings'] = df_filtered.apply(safety_checks, axis=1)

In [251]:
# 8. Space Efficiency Grade (how effectively a building's total floor area is utilized.)
df_filtered['space_efficiency_ratio'] = (df_filtered['carpetarea_sqft'] / df_filtered['superbuiltuparea_sqft']) * 100

bins = [0,60,80,100]
df_filtered['space_efficieny_grade'] = pd.cut(df_filtered['space_efficiency_ratio'], bins=bins, labels=['Poor Efficiency', 'Standard', 'High Efficiency'])
df_filtered.drop(columns=['space_efficiency_ratio'], inplace=True)

In [252]:
# 9. Family Segment
def family_wise(row):
    # A 'Family Ready' home has 2+ bhk, 2+ bathrooms, and reserved parking
    if row['bhk'] >= 3 and row['bathrooms'] >= 3 and str(row['parking']).lower() != 'none':
        return 'Large Family Choice'
    if row['bhk'] >= 2 and row['bathrooms'] >= 1:
        return 'Small Family/Couple'
    return 'Bachelor/Studio'

df_filtered['family_segment'] = df_filtered.apply(family_wise, axis=1)

In [253]:
# 10. Modernity index
def classify_modernity(row):
    score = 0
    # Amenity points
    if row['amenitiescount'] > 12: score += 2
    elif row['amenitiescount'] > 7: score += 1
    
    # Parking points
    if str(row['parking']).lower() in ['covered', 'basement', 'stilt']:
        score += 1

    # High Floor factor (Modern high-rises)
    if row['totalfloors'] > 15: score += 1    

    if score >= 3: return 'Ultra-Modern/Smart'
    if score >= 1: return 'Standard Modern'
    return 'Basic/Traditional'

df_filtered['modernity_index'] = df_filtered.apply(classify_modernity, axis=1)

In [254]:
# 11. Utility Balance (competition vs. confort)
df_filtered['bath_to_bhk_ratio'] = df_filtered['bathrooms'] / df_filtered['bhk']
df_filtered['parking_count'] = df_filtered['parking'].apply(lambda x:0 if str(x).lower() == 'none' else 1)

def investment_utility_signal(row):
    # Under-serviced (Bad for Investment)
    if row['bhk'] >= 3 and row['bath_to_bhk_ratio'] < 0.6: # A 2 BHK with 1 bathroom (ratio 0.5); high competition, reducing comfort.
        return 'Under-Serviced'
    
    # Luxury Balance (High Investment Potential)
    if row['bath_to_bhk_ratio'] >= 1.0 and row['parking_count'] >= 1:
        return 'High-Utility'
    
    return 'Standard Utility'

df_filtered['utility_balance'] = df_filtered.apply(investment_utility_signal, axis=1)
df_filtered.drop(columns=['bath_to_bhk_ratio', 'parking_count'], inplace=True)

In [255]:
# 12. FSI Category
def estimate_fsi_impact(row):
    # High-rise buildings have high FSI (more people sharing the same land)
    if row['totalfloors'] > 20:
        return 'High FSI (Dense Urban)'
    elif row['totalfloors'] > 5:
        return 'Medium FSI (Suburban Multi-story)'
    else:
        return 'Low FSI (Spacious/Independent)'

df_filtered['fsi_category'] = df_filtered.apply(estimate_fsi_impact, axis=1)

In [256]:
# 13. Low Density Premium
df_filtered['low_density_premium'] = np.where(
    (df_filtered['fsi_category'] == 'Low FSI (Spacious/Independent)') & 
    (df_filtered['price_category'] == 'Fair Market Value'), 
    'Rare Asset', 'Standard'
)

*By adding 10+ engineered features, we transformed raw numbers into "Investment Signals" that a buyer can actually understand.*
+ **price_per_sqft:** Standardized price unit; allows property price comparison.
+ **locality_avg_price_sqft:** The median price of similar properties in the same neighborhood; acts as the "Fair Market Value."
+ **price_deviation_pct:** The percentage difference between the listing price and the locality benchmark; identifies bargains or overpriced units.
+ **price_category:** Categorizes properties into 4 buckets (Underpriced to Overpriced) based on price quantiles.
+ **land_overlap_risk:** Geospatial check that flags multiple listings on the exact same coordinate to prevent fraud.
+ **structural_life_stage:** Classifies the building into stages like New, Mid-Life, Aging, and Redevelopment Needed based on age and building type.
+ **safety_rating:** A proprietary risk score (Verified, Caution, High Risk) combining RERA status, age, price suspicion, land overlap risk and lifespan of buildings.
+ **space_efficiency_grade:** Measures how much of the total area is actually usable (Carpet vs. Super Built-up ratio).
+ **family_segment:** Segments properties (Bachelor, Small Family, Large Family) based on BHK and bathroom counts.
+ **modernity_index:** Ranks properties by "Smart/Modern" features using amenity counts, parking types, and floor height.
+ **utility_balance:** A score determining if the ratio of bathrooms and parking to BHK is sufficient for high rental demand.
+ **fsi_category:** Categorized Floor Space Index into three segments (Low, Medium and High FSI) based on the total floors. More number of floors means dense population, because many people sharing same land.
+ **low_density_premium:** Flags "Rare Assets"—luxury properties with low building density in high-demand cities.
---

### __SQL Exploratory Data Analysis__

In [ ]:
# Saving this table into database from DataFrame (df_filtered)

import sqlalchemy
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:YOUR_PASSWORD_HERE@localhost/estate')

# Defining specific data types for MySQL to ensure efficiency
dtype_map = {
    'listingid': sqlalchemy.types.VARCHAR(50),
    'city': sqlalchemy.types.VARCHAR(100),
    'locality': sqlalchemy.types.VARCHAR(255),
    'propertytype': sqlalchemy.types.VARCHAR(100),
    'bhk': sqlalchemy.types.INT,
    'bathrooms': sqlalchemy.types.INT,
    'superbuiltuparea_sqft': sqlalchemy.types.DECIMAL(15,2),
    'carpetarea_sqft': sqlalchemy.types.DECIMAL(15,2),
    'totalfloors': sqlalchemy.types.INT,
    'parking': sqlalchemy.types.VARCHAR(50),
    'buildingtype': sqlalchemy.types.VARCHAR(100),
    'yearbuilt': sqlalchemy.types.INT,
    'ageyears': sqlalchemy.types.INT,
    'amenitiescount': sqlalchemy.types.INT,
    'isreraregistered': sqlalchemy.types.VARCHAR(100),
    'reraid': sqlalchemy.types.VARCHAR(100),
    'latitude': sqlalchemy.types.Float,
    'longitude': sqlalchemy.types.Float,
    'price_inr': sqlalchemy.types.DECIMAL(15, 2),
    'price_per_sqft': sqlalchemy.types.DECIMAL(12, 2),
    'locality_avg_price_per_sqft': sqlalchemy.types.DECIMAL(12, 2),
    'price_deviation_pct': sqlalchemy.types.Float,
    'price_category': sqlalchemy.types.VARCHAR(50),
    'land_overlap_risk': sqlalchemy.types.VARCHAR(50),
    'structural_life_stage': sqlalchemy.types.VARCHAR(50),
    'safety_rating': sqlalchemy.types.VARCHAR(50),
    'space_efficiency_grade': sqlalchemy.types.VARCHAR(50),
    'family_segment': sqlalchemy.types.VARCHAR(50),
    'modernity_index': sqlalchemy.types.VARCHAR(50),
    'utility_balance': sqlalchemy.types.VARCHAR(100),
    'fsi_category': sqlalchemy.types.VARCHAR(50),
    'low_density_premium': sqlalchemy.types.VARCHAR(100)
}

# Exporting to MySQL
try:
    df_filtered.to_sql('processed_property_data', 
              con=engine, 
              if_exists='replace', 
              index=False, 
              dtype=dtype_map)
    print("Success! 'processed_property_data' table created in MySQL.")
except Exception as e:
    print(f"Error: {e}")

Success! 'processed_property_data' table created in MySQL.

*We loaded our clean data into a MySQL database to run complex business queries.*